name: Fork Notification

on:
  fork:
  
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Notify about fork
        uses: ./.github/actions/slack-notification
        with:
          github_repo_url: ${{ github.event.repository.html_url }}
          github_username: ${{ github.actor }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
